{
  path_index : "data/index",
  path_index_images : "data/index-image",
  path_index_images_own_domain : "data/index-image",
  path_dataset : "data/acl-publication-info.74k.parquet",
  path_model : "/bigwork/nhwpajjy/pre-trained-models/DeepSeek-R1-Distill-Qwen-1.5B",
  webserver_ip: "34.204.191.141",
  path_index_own_domain : "data/index-debug",
  path_dataset_own_domain : "data/argument-mining",
  path_dataset_cache : "data/cache/",
  path_artifacts: "data/artifacts",
  "own_domain": True,
  "chunk_size": 1024,
  "embedding_model_id": "sentence-transformers/allenai-specter",
  "caption_embedding_model_id": "cross-encoder/ms-marco-MiniLM-L6-v2",
  "k": 20,
  "temperature": 0.6
}